### ISSUE TITLE
Program Crashes

### ISSUE THREAD

**Issue by AtjonTV** [TrezarCoin/TrezarCoin#1]
I tryed to start the Wallet in Wine on Ubuntu 16.04 and got the following error (I installed the base Components of MinGW onto the Wine System, but still got the crash)

> My System:
ElemantaryOS 0.4.1 (Loki) -> Based on Ubuntu 16.04 LTS 64bit
Windows Runtime -> Wine wine-1.6.2
Hardware -> Intel Core i7-6500U, 8GB RAM

> Backtrace:
0x7bc77048 DbgBreakPoint in ntdll: int	$3
Modules:
Module	Address			Debug info	Name (109 modules)
PE	  400000- 1685000	Export          trezarcoin-qt
ELF	7b800000-7ba54000	Deferred        kernel32<elf>
  \-PE	7b810000-7ba54000	\               kernel32
ELF	7bc00000-7bcda000	Dwarf           ntdll<elf>
  \-PE	7bc10000-7bcda000	\               ntdll
ELF	7bf00000-7bf04000	Deferred        <wine-loader>
ELF	7d0b4000-7d0bb000	Deferred        libnss_dns.so.2
ELF	7d201000-7d217000	Deferred        libgpg-error.so.0
ELF	7d217000-7d28c000	Deferred        libpcre.so.3
ELF	7d28c000-7d2a9000	Deferred        libgcc_s.so.1
ELF	7d2a9000-7d358000	Deferred        libgcrypt.so.20
ELF	7d358000-7d37e000	Deferred        liblzma.so.5
ELF	7d37e000-7d387000	Deferred        librt.so.1
ELF	7d387000-7d3ad000	Deferred        libselinux.so.1
ELF	7d3ad000-7d43b000	Deferred        libsystemd.so.0
ELF	7d43b000-7d444000	Deferred        libffi.so.6
ELF	7d444000-7d45d000	Deferred        libresolv.so.2
ELF	7d45d000-7d4b7000	Deferred        libdbus-1.so.3
ELF	7d4b7000-7d543000	Deferred        libgmp.so.10
ELF	7d543000-7d578000	Deferred        libhogweed.so.4
ELF	7d578000-7d5b5000	Deferred        libnettle.so.6
ELF	7d5b5000-7d5ca000	Deferred        libtasn1.so.6
ELF	7d5ca000-7d5fe000	Deferred        libidn.so.11
ELF	7d5fe000-7d65f000	Deferred        libp11-kit.so.0
ELF	7d65f000-7d66c000	Deferred        libkrb5support.so.0
ELF	7d66c000-7d69d000	Deferred        libk5crypto.so.3
ELF	7d69d000-7d773000	Deferred        libkrb5.so.3
ELF	7d773000-7d787000	Deferred        libavahi-client.so.3
ELF	7d787000-7d8df000	Deferred        libgnutls.so.30
ELF	7d8df000-7d931000	Deferred        libgssapi_krb5.so.2
ELF	7d931000-7d9b8000	Deferred        libcups.so.2
ELF	7d9b8000-7d9d6000	Deferred        wintab32<elf>
  \-PE	7d9c0000-7d9d6000	\               wintab32
ELF	7d9d6000-7da0b000	Deferred        uxtheme<elf>
  \-PE	7d9e0000-7da0b000	\               uxtheme
ELF	7da0b000-7da16000	Deferred        libxcursor.so.1
ELF	7da16000-7db61000	Deferred        libx11.so.6
ELF	7dbc1000-7dbc8000	Deferred        libxfixes.so.3
ELF	7dbc8000-7dbdb000	Deferred        libxi.so.6
ELF	7dbdb000-7dbdf000	Deferred        libxcomposite.so.1
ELF	7dbdf000-7dbec000	Deferred        libxrandr.so.2
ELF	7dbec000-7dbf8000	Deferred        libxrender.so.1
ELF	7dbf8000-7dbff000	Deferred        libxxf86vm.so.1
ELF	7dbff000-7dc03000	Deferred        libxinerama.so.1
ELF	7dc03000-7dc0a000	Deferred        libxdmcp.so.6
ELF	7dc0a000-7dc0e000	Deferred        libxau.so.6
ELF	7dc0e000-7dc34000	Deferred        libxcb.so.1
ELF	7dc34000-7dc49000	Deferred        libxext.so.6
ELF	7dc4d000-7dc52000	Deferred        libkeyutils.so.1
ELF	7dc52000-7dc57000	Deferred        libcom_err.so.2
ELF	7dc57000-7dc65000	Deferred        libavahi-common.so.3
ELF	7dc67000-7dcf4000	Deferred        winex11<elf>
  \-PE	7dc70000-7dcf4000	\               winex11
ELF	7ddc6000-7ddf0000	Deferred        libexpat.so.1
ELF	7ddf0000-7de39000	Deferred        libfontconfig.so.1
ELF	7de39000-7de64000	Deferred        libpng12.so.0
ELF	7de64000-7de7f000	Deferred        libz.so.1
ELF	7de7f000-7df2f000	Deferred        libfreetype.so.6
ELF	7df2f000-7df52000	Deferred        libtinfo.so.5
ELF	7df52000-7df78000	Deferred        libncurses.so.5
ELF	7df96000-7dfc0000	Deferred        msacm32<elf>
  \-PE	7dfa0000-7dfc0000	\               msacm32
ELF	7dfc0000-7e078000	Deferred        winmm<elf>
  \-PE	7dfd0000-7e078000	\               winmm
ELF	7e078000-7e1a5000	Deferred        oleaut32<elf>
  \-PE	7e090000-7e1a5000	\               oleaut32
ELF	7e1a5000-7e221000	Deferred        rpcrt4<elf>
  \-PE	7e1b0000-7e221000	\               rpcrt4
ELF	7e221000-7e350000	Deferred        ole32<elf>
  \-PE	7e240000-7e350000	\               ole32
ELF	7e350000-7e384000	Deferred        ws2_32<elf>
  \-PE	7e360000-7e384000	\               ws2_32
ELF	7e384000-7e399000	Deferred        mswsock<elf>
  \-PE	7e390000-7e399000	\               mswsock
ELF	7e399000-7e448000	Dwarf           msvcrt<elf>
  \-PE	7e3b0000-7e448000	\               msvcrt
ELF	7e448000-7e46d000	Deferred        iphlpapi<elf>
  \-PE	7e450000-7e46d000	\               iphlpapi
ELF	7e46d000-7e491000	Deferred        imm32<elf>
  \-PE	7e470000-7e491000	\               imm32
ELF	7e491000-7e4cd000	Deferred        winspool<elf>
  \-PE	7e4a0000-7e4cd000	\               winspool
ELF	7e4cd000-7e5c2000	Deferred        comctl32<elf>
  \-PE	7e4d0000-7e5c2000	\               comctl32
ELF	7e5c2000-7e6d9000	Deferred        gdi32<elf>
  \-PE	7e5d0000-7e6d9000	\               gdi32
ELF	7e6d9000-7e827000	Deferred        user32<elf>
  \-PE	7e6f0000-7e827000	\               user32
ELF	7e827000-7e89d000	Deferred        shlwapi<elf>
  \-PE	7e830000-7e89d000	\               shlwapi
ELF	7e89d000-7eac6000	Deferred        shell32<elf>
  \-PE	7e8b0000-7eac6000	\               shell32
ELF	7eac6000-7ebab000	Deferred        comdlg32<elf>
  \-PE	7ead0000-7ebab000	\               comdlg32
ELF	7ebab000-7ec17000	Deferred        advapi32<elf>
  \-PE	7ebc0000-7ec17000	\               advapi32
ELF	7ef48000-7ef5b000	Deferred        libnss_files.so.2
ELF	7ef5b000-7ef68000	Deferred        libnss_nis.so.2
ELF	7ef68000-7ef83000	Deferred        libnsl.so.1
ELF	7ef83000-7ef8d000	Deferred        libnss_compat.so.2
ELF	7ef8d000-7efe2000	Deferred        libm.so.6
ELF	7efe7000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f73c1000-f73c6000	Deferred        libdl.so.2
ELF	f73c6000-f757c000	Deferred        libc.so.6
ELF	f757d000-f759a000	Deferred        libpthread.so.0
ELF	f75b8000-f776d000	Dwarf           libwine.so.1
ELF	f776f000-f7794000	Deferred        ld-linux.so.2
ELF	f7796000-f7797000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) Z:\home\atjontv\Downloads\Trezarcoin\trezarcoin-qt.exe
	00000034    0
	00000033    0
	00000032    0
	00000031   -2
	00000030    0
	0000002f   -1
	0000002e    0
	0000002d    0
	0000002c    0
	0000002b    0
	0000002a    0
	00000026    0
	00000025    0
	00000009    0 <==
0000000e services.exe
	0000001f    0
	0000001e    0
	00000014    0
	00000010    0
	0000000f    0
00000012 winedevice.exe
	0000001b    0
	0000001a    0
	00000017    0
	00000013    0
0000001c plugplay.exe
	00000021    0
	00000020    0
	0000001d    0
00000022 explorer.exe
	00000024    0
	00000023    0
System information:
    Wine build: wine-1.6.2
    Platform: i386 (WOW64)
    Host system: Linux
    Host version: 4.10.0-33-generic

**Comment by aciddude** [comment]
if you're on ubuntu why not just built the ubuntu/linux version instead ?

**Comment by AtjonTV** [comment]
There are some libs missing:

`./trezarcoin-qt: error while loading shared libraries: libminiupnpc.so.10: cannot open shared object file: No such file or directory`

Do you have a Shell Script to install them in one go? 😐

**Comment by gp2015** [comment]
To get the libraries, maybe try something along the lines of:

`sudo ln -s /usr/lib/x86_64-linux-gnu/libminiupnpc.so.10 /usr/lib/x86_64-linux-gnu/libminiupnpc.so.8`

Source:
https://github.com/bitconnectcoin/bitconnectcoin/issues/3

**Comment by aciddude** [comment]
@AtjonTV  - are you still experiencing issues ?

**Comment by aciddude** [comment]
Closed due to inactivity  - builds are also easier in v1.2 which is the latest supported release.
