### ISSUE TITLE
Balance is 0 after I updated wallet to 1.2.0 and copied my old wallet.dat file

### ISSUE THREAD

**Issue by jenkap** [TrezarCoin/TrezarCoin#27]
Hi
Just updated my Trezarcoin wallet to v1.2 but balance shows 0.
Am I missing something here? Any help will be much appreciated.
Thanks

**Comment by ChekaZ** [comment]
Restart your wallet with -zapwallettxes=1, or download the newest version 1.2.1 and type zapwallettxes into the console.

**Comment by jenkap** [comment]
Hi
  I have downloaded v1.2.1 and tried your suggestion, but balance is still 0.
  Any other options to get my trezarcoin back.
  Thanks
  Jenka
  
  
  ------ Reply to message --------
  
  Date: Sun, 24 Mar 2019 17:45:43 0200
  
  From: notifications@github.com
  
  CC: jenkap , Author , 
  
  
  
   Restart your wallet with -zapwallettxes=1, or download the newest version 1.2.1 and type zapwallettxes into the console.

**Comment by jenkap** [comment]
I got it working now.
Thanks
 

----- Reply to message -----
Subject: Re: [TrezarCoin/TrezarCoin] Balance is 0 after I updated wallet to 1.2.0 and copied my old wallet.dat file (#27)
Date: svētd., 24 marts, 17:45
