### ISSUE TITLE
bitcoin miner detected in qt wallet

### ISSUE THREAD

**Issue by fletchuk1** [TrezarCoin/TrezarCoin#3]
I'm interested in your project and downloaded the windows wallet but my AV (Sophos) detected a bitcoin miner in the install file.

Any comments?

**Comment by ghostlander** [comment]
Another false positive. By the way, there is no install file. This is the actual executable.

**Comment by fletchuk1** [comment]
Thanks for the reassurance,

Mark.

**Comment by olegaix** [comment]
what false positive might that be and where are the binaries?! what exactly is there in the code that windows flags as an unwanted softare?

**Comment by aciddude** [comment]
@olegaix  -  The false positive is that older versions of Bitcoin source code contained a small CPU miner. 

As trezarcoin moves to newer code, we will remove the inbuilt miner, and this will stop antiviruses flagging  the EXE as a virus.
