### ISSUE TITLE
ERROR: CheckBlock() : first tx is not coinbase

### ISSUE THREAD

**Issue by xD0135** [TrezarCoin/TrezarCoin#5]
Hi, I'm always getting the following error when new blocks are found and I hope you can help me:

```
ThreadRPCServer method=submitblock
ERROR: CheckBlock() : first tx is not coinbase
ERROR: ProcessBlock() : CheckBlock FAILED
```

It doesn't matter if I try with YiiMP, NOMP, UNOMP the results are the same.

This is my trezarcoin.conf file:

```
rpcuser=<user>
rpcpassword=<password>
server=1
listen=1
daemon=1
gen=1
rpcport=6003
stakegen=1
irc=1
dns=1
txindex=1
staking=1
```

I've tried all possible combinations of enabling/disabling and the results are all the same.

Thanks in advance.

**Comment by ghostlander** [comment]
The first transaction of any proof-of-work block must be a coin base. If your pool has a problem with it, try getblocktemplate mode submit instead of submitblock.

**Comment by xD0135** [comment]
Thanks @ghostlander, let me try that and will let you know shortly. Note that I only have this issue with PoW/PoS hybrid coins but PoW-only coins seem to work just fine.

If `getblocktemplate` required for hybrid coins?

**Comment by ghostlander** [comment]
Not required, but one of these two should work at least.
