### ISSUE TITLE
Shows load screen and then exits silently

### ISSUE THREAD

**Issue by VandeurenGlenn** [TrezarCoin/TrezarCoin#6]
Wallet doesn't open anymore after a windows restart.

This is on Windows 10 (64)

**Comment by VandeurenGlenn** [comment]
Thanks to quick response of the support channel on Slack, I was able to get it running again following these steps.

- backup wallet.dat (copy)
- delete/rename data folder

**Comment by aciddude** [comment]
great!  Going to close this now.
