### ISSUE TITLE
Program Crashes 

### ISSUE THREAD

**Issue by MtaTech** [TrezarCoin/TrezarCoin#9]
Program Crashes / 10sc after working. trezarcoin-qt start , minize and closed. how to fixed ?

**Comment by mkapusnik** [comment]
Hey guys,
I'm experiencing the same issue since yesterday. After about a minute, wallet crashes with:

```
trezarcoin-qt: table/table_builder.cc:97: void leveldb::TableBuilder::Add(const leveldb::Slice&, const leveldb::Slice&): Assertion `r->options.comparator->Compare(key, Slice(r->last_key)) > 0' failed.

/usr/bin/trezarcoin: line 3: 27191 Aborted                 trezarcoin-qt -datadir=$dir -conf=$dir/trezarcoin.conf
```

Running on Raspberry Pi B - don't know if it's related.

**Comment by kaskii** [comment]
@mkapusnik Try launching the wallet with -reindex argument

`./trezarcoin-qt -reindex`

**Comment by mkapusnik** [comment]
@kaskii Thanks for advice. I solved it by deleting everything except wallet.dat. But I guess that's just a more cruel way of -reindex :).
Anyways, my point was mainly to provide stacktrace so that devs have something to start with.
